# Конфигурация линтера Ruff

# Запускать все правила
select = ["ALL"]
# за исключением перечисленных ниже:
ignore = [
    "D",      # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "T20",    # https://docs.astral.sh/ruff/rules/#flake8-print-t20
    "RET504", # https://docs.astral.sh/ruff/rules/unnecessary-assign/
]

# Разрешаются кириллические буквы, похожие на латинские.
# https://docs.astral.sh/ruff/settings/#allowed-confusables
allowed-confusables = [
    "А", "В", "Н", "О", "У",
    "а", "б", "г", "е", "о", "р", "с", "у",
]

# Стиль строк документации.
# [https://docs.astral.sh/ruff/rules/#pydocstyle-d]
# [https://docs.astral.sh/ruff/settings/#pydocstyle]
[pydocstyle]
convention = "google"
